-- VHDL Entity Ali.FSM_Sequence_Detector.symbol
--
-- Created:
--          by - Lab 107.UNKNOWN (DESKTOP-7DIT156)
--          at - 21:09:29 11/30/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY FSM_Sequence_Detector IS
   PORT( 
      clk : IN     std_logic;
      rst : IN     std_logic;
      x   : IN     std_logic;
      y   : OUT    std_logic
   );

-- Declarations

END FSM_Sequence_Detector ;

--
-- VHDL Architecture Ali.FSM_Sequence_Detector.fsm
--
-- Created:
--          by - Lab 107.UNKNOWN (DESKTOP-7DIT156)
--          at - 21:09:29 11/30/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF FSM_Sequence_Detector IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state,
      x
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN s0 => 
            IF (x = '0') THEN 
               next_state <= s0;
            ELSIF (x = '1') THEN 
               next_state <= s1;
            ELSE
               next_state <= s0;
            END IF;
         WHEN s1 => 
            IF (x = '0') THEN 
               next_state <= s1;
            ELSIF (x = '1') THEN 
               next_state <= s2;
            ELSE
               next_state <= s1;
            END IF;
         WHEN s2 => 
            IF (x = '0') THEN 
               next_state <= s1;
            ELSIF (x = '1') THEN 
               next_state <= s3;
            ELSE
               next_state <= s2;
            END IF;
         WHEN s3 => 
            IF (x = '0') THEN 
               next_state <= s1;
            ELSIF (x = '1') THEN 
               next_state <= s0;
            ELSE
               next_state <= s3;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN s0 => 
            y <= '0' ;
         WHEN s1 => 
            y <= '0' ;
         WHEN s2 => 
            y <= '0' ;
         WHEN s3 => 
            y <= '1' ;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
END fsm;
