-- VHDL Entity Ali.fulladder.symbol
--
-- Created:
--          by - Lab 107.UNKNOWN (DESKTOP-7DIT156)
--          at - 20:13:40 06/11/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY fulladder IS
   PORT( 
      A    : IN     std_logic;
      B    : IN     std_logic;
      Cin  : IN     std_logic;
      Cout : OUT    std_logic;
      Sum  : OUT    std_logic
   );

-- Declarations

END fulladder ;

--
-- VHDL Architecture Ali.fulladder.struct
--
-- Created:
--          by - Lab 107.UNKNOWN (DESKTOP-7DIT156)
--          at - 20:13:40 06/11/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Ali;

ARCHITECTURE struct OF fulladder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Cout1 : std_logic;
   SIGNAL Cout2 : std_logic;
   SIGNAL Sum1  : std_logic;


   -- Component Declarations
   COMPONENT half_adder
   PORT (
      A    : IN     std_logic;
      B    : IN     std_logic;
      Cout : OUT    std_logic;
      Sum  : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : half_adder USE ENTITY Ali.half_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_3' of 'or1'
   Cout <= Cout2 OR Cout1;

   -- Instance port mappings.
   U_0 : half_adder
      PORT MAP (
         A    => A,
         B    => B,
         Sum  => Sum1,
         Cout => Cout1
      );
   U_1 : half_adder
      PORT MAP (
         A    => Sum1,
         B    => Cin,
         Sum  => Sum,
         Cout => Cout2
      );

END struct;
