-- VHDL Entity Ali.Mux_4_to_1_using_Mux_2_to_1.symbol
--
-- Created:
--          by - Lab 107.UNKNOWN (DESKTOP-7DIT156)
--          at - 21:03:55 10/23/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY Mux_4_to_1_using_Mux_2_to_1 IS
   PORT( 
      ins    : IN     std_logic_vector (3 DOWNTO 0);
      sel    : IN     std_logic_vector (1 DOWNTO 0);
      output : OUT    std_logic
   );

-- Declarations

END Mux_4_to_1_using_Mux_2_to_1 ;

--
-- VHDL Architecture Ali.Mux_4_to_1_using_Mux_2_to_1.struct
--
-- Created:
--          by - Lab 107.UNKNOWN (DESKTOP-7DIT156)
--          at - 21:03:55 10/23/2023
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2007.1 (Build 19)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY Ali;

ARCHITECTURE struct OF Mux_4_to_1_using_Mux_2_to_1 IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL a_or_b_out : std_logic;
   SIGNAL c_or_d     : std_logic;


   -- Component Declarations
   COMPONENT Mux_2_to_1
   PORT (
      sel : IN     std_logic;
      x   : IN     std_logic;
      y   : IN     std_logic;
      z   : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Mux_2_to_1 USE ENTITY Ali.Mux_2_to_1;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : Mux_2_to_1
      PORT MAP (
         x   => ins(0),
         y   => ins(1),
         sel => sel(0),
         z   => a_or_b_out
      );
   U_1 : Mux_2_to_1
      PORT MAP (
         x   => a_or_b_out,
         y   => c_or_d,
         sel => sel(1),
         z   => output
      );
   U_2 : Mux_2_to_1
      PORT MAP (
         x   => ins(2),
         y   => ins(3),
         sel => sel(0),
         z   => c_or_d
      );

END struct;
